#!/usr/bin/env python3
"""
Check if Streamlit authentication is properly configured.
Run this with: streamlit run check_auth_config.py
"""
import streamlit as st

st.title("🔐 Authentication Configuration Check")

st.markdown("---")

# Check if st.user exists
st.header("1. Check st.user Availability")
if hasattr(st, 'user'):
    st.success("✅ `st.user` is available")

    # Check user attributes
    st.subheader("User Attributes:")
    if hasattr(st.user, 'is_logged_in'):
        st.write(f"- `is_logged_in`: {st.user.is_logged_in}")
    else:
        st.warning("- `is_logged_in` not available")

    if hasattr(st.user, 'email'):
        st.write(f"- `email`: {st.user.email if st.user.email else 'Not set'}")
    else:
        st.warning("- `email` not available")

    if hasattr(st.user, 'name'):
        st.write(f"- `name`: {st.user.name if st.user.name else 'Not set'}")
    else:
        st.warning("- `name` not available")
else:
    st.error("❌ `st.user` is NOT available")
    st.info("This means authentication is not configured in Streamlit Cloud.")

st.markdown("---")

# Check if st.login exists
st.header("2. Check st.login Availability")
if hasattr(st, 'login'):
    st.success("✅ `st.login()` is available")
else:
    st.error("❌ `st.login()` is NOT available")
    st.info("This means authentication is not configured in Streamlit Cloud.")

st.markdown("---")

# Check if st.logout exists
st.header("3. Check st.logout Availability")
if hasattr(st, 'logout'):
    st.success("✅ `st.logout()` is available")
else:
    st.error("❌ `st.logout()` is NOT available")

st.markdown("---")

# Environment check
st.header("4. Environment Information")
import os
st.write(f"- Running on: {'Streamlit Cloud' if os.getenv('STREAMLIT_SHARING_MODE') else 'Local'}")

# Check session state
st.header("5. Session State")
if hasattr(st, 'session_state'):
    st.success("✅ `st.session_state` is available")
    st.write("Session state keys:", list(st.session_state.keys()))
else:
    st.error("❌ `st.session_state` is NOT available")

st.markdown("---")

# Instructions
st.header("📋 What This Means")

if not hasattr(st, 'user') or not hasattr(st, 'login'):
    st.error("""
    ### ❌ Authentication NOT Configured

    Your app doesn't have authentication enabled. To fix this:

    1. Go to https://share.streamlit.io/
    2. Click on your app
    3. Click the menu (⋮) → **Settings**
    4. Scroll to **"Authentication"** section
    5. Toggle **"Require viewers to authenticate"** to ON
    6. Select **"Google OAuth"**
    7. Click **"Save"**
    8. Wait for the app to redeploy (1-2 minutes)

    After this, the Google login should work!
    """)
else:
    if hasattr(st.user, 'is_logged_in') and st.user.is_logged_in:
        st.success("""
        ### ✅ Authentication Working!

        You are successfully logged in with Google OAuth.
        """)
    else:
        st.warning("""
        ### ⚠️ Authentication Configured But Not Logged In

        Authentication is configured, but you're not logged in yet.
        Try clicking a login button to test the flow.
        """)

        if st.button("🔑 Test Login"):
            if hasattr(st, 'login'):
                st.login()
            else:
                st.error("st.login() not available")

st.markdown("---")
st.caption("Generated by Claude Code to help diagnose authentication issues.")
